services:
  db:
    container_name: academic_blog_db
    image: postgres:latest
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: academic_blog_db
    volumes:
      - academic_blog_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - production_network

  api:
    container_name: academic_blog_api
    build:
      context: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 123456
      DB_NAME: academic_blog_db
      DB_NAME_TEST: academic_blog_db_test
      JWT_SECRET: academicblogapi2024
    ports:
      - "3000:3000"
    networks:
      - production_network

networks:
  production_network:
    driver: bridge

volumes:
  academic_blog_db_data: